// <auto-generated />
using System;
using CHHA_PlanOfCorrectionAudit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHHA_PlanOfCorrectionAudit.Migrations
{
    [DbContext(typeof(CHHA_PlanOfCorrectionAuditContext))]
    [Migration("20250603165442_nullable")]
    partial class nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CHHA_PlanOfCorrectinAudit.Models.CHHA_Quality_POC_Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assigned_Reviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Borough_of_Care")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Date_Assigned")
                        .HasColumnType("date");

                    b.Property<string>("Financial_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_MRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Start_of_Care_Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("CHHA_Quality_POC_Metadata");
                });

            modelBuilder.Entity("CHHA_PlanOfCorrectinAudit.Models.CHHA_Quality_POC_Responses", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<DateOnly?>("Date_Assigned")
                        .HasColumnType("date");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetadataId")
                        .HasColumnType("int");

                    b.Property<string>("Patient_MRN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponseId");

                    b.HasIndex("MetadataId");

                    b.ToTable("CHHA_Quality_POC_Responses");
                });

            modelBuilder.Entity("CHHA_PlanOfCorrectinAudit.Models.CHHA_Quality_POC_Responses", b =>
                {
                    b.HasOne("CHHA_PlanOfCorrectinAudit.Models.CHHA_Quality_POC_Metadata", "Metadata")
                        .WithMany("Responses")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("CHHA_PlanOfCorrectinAudit.Models.CHHA_Quality_POC_Metadata", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
